PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations VALUES(3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(4,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2026_05_21_000001_create_profiles_table',1);
INSERT INTO migrations VALUES(6,'2026_05_21_000002_create_skills_table',1);
INSERT INTO migrations VALUES(7,'2026_05_21_000003_create_projects_table',1);
INSERT INTO migrations VALUES(8,'2026_05_21_000004_create_experiences_table',1);
INSERT INTO migrations VALUES(9,'2026_05_21_000005_create_contact_messages_table',1);
INSERT INTO migrations VALUES(10,'2026_05_21_000006_create_hobbies_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO users VALUES(1,'Vano Admin','admin@vano.test',NULL,'$2y$10$odCRuM2sOKKlizBdFBgpmOoDG1m5iOmJHqDuoKQINPuaL3plRX3wq',NULL,'2026-05-21 01:30:06','2026-05-21 01:30:06');
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer not null primary key autoincrement, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime default CURRENT_TIMESTAMP not null);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer not null primary key autoincrement, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "profiles" ("id" integer not null primary key autoincrement, "name" varchar not null, "headline" varchar not null, "bio" text, "email" varchar, "phone" varchar, "location" varchar, "avatar_url" varchar, "social_links" text, "created_at" datetime, "updated_at" datetime);
INSERT INTO profiles VALUES(1,'Vano','Web Developer & UI Builder','Developer yang fokus membangun website portfolio, dashboard, dan aplikasi web yang rapi, cepat, dan mudah digunakan.','hello@vano.test','+62 812 0000 0000','Jakarta, Indonesia','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80','{"github":"https:\/\/github.com\/vano","linkedin":"https:\/\/linkedin.com\/in\/vano","instagram":"https:\/\/instagram.com\/vano"}','2026-05-21 01:30:06','2026-05-21 01:30:06');
CREATE TABLE IF NOT EXISTS "skills" ("id" integer not null primary key autoincrement, "name" varchar not null, "category" varchar not null, "level" varchar, "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO skills VALUES(1,'ReactJS','Frontend','Advanced',1,'2026-05-21 01:30:06','2026-05-21 01:30:06');
INSERT INTO skills VALUES(2,'Laravel','Backend','Advanced',2,'2026-05-21 01:30:06','2026-05-21 01:30:06');
INSERT INTO skills VALUES(3,'REST API','Backend','Advanced',3,'2026-05-21 01:30:06','2026-05-21 01:30:06');
INSERT INTO skills VALUES(4,'UI Implementation','Frontend','Intermediate',4,'2026-05-21 01:30:07','2026-05-21 01:30:07');
INSERT INTO skills VALUES(5,'Database Design','Backend','Intermediate',5,'2026-05-21 01:30:07','2026-05-21 01:30:07');
CREATE TABLE IF NOT EXISTS "projects" ("id" integer not null primary key autoincrement, "title" varchar not null, "slug" varchar not null, "summary" varchar not null, "description" text, "tech_stack" text, "demo_url" varchar, "repository_url" varchar, "image_url" varchar, "is_featured" tinyint(1) not null default '0', "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO projects VALUES(1,'Portfolio React + Laravel','portfolio-react-laravel','Portfolio personal Vano dengan admin CMS dan auth Laravel.','Website portfolio full-stack untuk Vano yang memisahkan frontend React Vite dan backend Laravel API. Admin dapat mengelola project, skill, experience, profil, dan pesan kontak.','["ReactJS","Vite","Laravel","Sanctum","SQLite"]','https://example.com','https://github.com/example/portfolio','https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',1,1,'2026-05-21 01:30:07','2026-05-21 01:30:07');
INSERT INTO projects VALUES(2,'Booking Dashboard','booking-dashboard','Dashboard reservasi dengan laporan dan manajemen jadwal.','Aplikasi dashboard untuk memantau booking, status pembayaran, jadwal, dan laporan operasional.','["ReactJS","Laravel","MySQL"]',NULL,NULL,'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',0,2,'2026-05-21 01:30:07','2026-05-21 01:30:07');
CREATE TABLE IF NOT EXISTS "experiences" ("id" integer not null primary key autoincrement, "title" varchar not null, "organization" varchar not null, "location" varchar, "start_date" varchar not null, "end_date" varchar, "description" text, "type" varchar not null default 'work', "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO experiences VALUES(1,'Full Stack Developer','Freelance','Remote','2024','Present','Membangun website, dashboard, dan API untuk kebutuhan bisnis kecil sampai menengah.','work',1,'2026-05-21 01:30:07','2026-05-21 01:30:07');
CREATE TABLE IF NOT EXISTS "contact_messages" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "subject" varchar not null, "message" text not null, "is_read" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "hobbies" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" text, "icon" varchar, "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO hobbies VALUES(1,'Ngoding','Mencoba ide web baru, membangun komponen UI, dan belajar pola backend yang lebih rapi.','Code',1,'2026-05-21 01:30:07','2026-05-21 01:30:07');
INSERT INTO hobbies VALUES(2,'Desain UI','Merapikan layout, warna, dan interaksi agar pengalaman website terasa lebih nyaman.','Palette',2,'2026-05-21 01:30:07','2026-05-21 01:30:07');
INSERT INTO hobbies VALUES(3,'Game','Bermain game untuk refreshing sekaligus melatih strategi dan problem solving.','Gamepad2',3,'2026-05-21 01:30:07','2026-05-21 01:30:07');
INSERT INTO sqlite_sequence VALUES('migrations',10);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('profiles',1);
INSERT INTO sqlite_sequence VALUES('skills',5);
INSERT INTO sqlite_sequence VALUES('hobbies',3);
INSERT INTO sqlite_sequence VALUES('projects',2);
INSERT INTO sqlite_sequence VALUES('experiences',1);
INSERT INTO sqlite_sequence VALUES('personal_access_tokens',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE UNIQUE INDEX "projects_slug_unique" on "projects" ("slug");
COMMIT;
